# frozen_string_literal: true

PayoutTable.destroy_all

PayoutTable.create(place: 1, players_paid: 2, percent: 60)
PayoutTable.create(place: 2, players_paid: 2, percent: 40)

PayoutTable.create(place: 1, players_paid: 3, percent: 50)
PayoutTable.create(place: 2, players_paid: 3, percent: 30)
PayoutTable.create(place: 3, players_paid: 3, percent: 20)

PayoutTable.create(place: 1, players_paid: 4, percent: 45)
PayoutTable.create(place: 2, players_paid: 4, percent: 25)
PayoutTable.create(place: 3, players_paid: 4, percent: 18)
PayoutTable.create(place: 4, players_paid: 4, percent: 12)

PayoutTable.create(place: 1, players_paid: 5, percent: 40)
PayoutTable.create(place: 2, players_paid: 5, percent: 23)
PayoutTable.create(place: 3, players_paid: 5, percent: 16)
PayoutTable.create(place: 4, players_paid: 5, percent: 12)
PayoutTable.create(place: 5, players_paid: 5, percent: 9)

PayoutTable.create(place: 1, players_paid: 6, percent: 38)
PayoutTable.create(place: 2, players_paid: 6, percent: 22)
PayoutTable.create(place: 3, players_paid: 6, percent: 15)
PayoutTable.create(place: 4, players_paid: 6, percent: 11)
PayoutTable.create(place: 5, players_paid: 6, percent: 8)
PayoutTable.create(place: 6, players_paid: 6, percent: 6)

PayoutTable.create(place: 1, players_paid: 7, percent: 35)
PayoutTable.create(place: 2, players_paid: 7, percent: 21)
PayoutTable.create(place: 3, players_paid: 7, percent: 15)
PayoutTable.create(place: 4, players_paid: 7, percent: 11)
PayoutTable.create(place: 5, players_paid: 7, percent: 8)
PayoutTable.create(place: 6, players_paid: 7, percent: 6)
PayoutTable.create(place: 7, players_paid: 7, percent: 4)

PayoutTable.create(place: 1, players_paid: 8, percent: 33.5)
PayoutTable.create(place: 2, players_paid: 8, percent: 20)
PayoutTable.create(place: 3, players_paid: 8, percent: 14.5)
PayoutTable.create(place: 4, players_paid: 8, percent: 11)
PayoutTable.create(place: 5, players_paid: 8, percent: 8)
PayoutTable.create(place: 6, players_paid: 8, percent: 6)
PayoutTable.create(place: 7, players_paid: 8, percent: 4)
PayoutTable.create(place: 8, players_paid: 8, percent: 3)

PayoutTable.create(place: 1, players_paid: 9, percent: 32)
PayoutTable.create(place: 2, players_paid: 9, percent: 19.5)
PayoutTable.create(place: 3, players_paid: 9, percent: 14)
PayoutTable.create(place: 4, players_paid: 9, percent: 11)
PayoutTable.create(place: 5, players_paid: 9, percent: 8)
PayoutTable.create(place: 6, players_paid: 9, percent: 6)
PayoutTable.create(place: 7, players_paid: 9, percent: 4)
PayoutTable.create(place: 8, players_paid: 9, percent: 3)
PayoutTable.create(place: 9, players_paid: 9, percent: 2.5)

PayoutTable.create(place: 1, players_paid: 10, percent: 31.75)
PayoutTable.create(place: 2, players_paid: 10, percent: 19.25)
PayoutTable.create(place: 3, players_paid: 10, percent: 13.75)
PayoutTable.create(place: 4, players_paid: 10, percent: 10.75)
PayoutTable.create(place: 5, players_paid: 10, percent: 7.75)
PayoutTable.create(place: 6, players_paid: 10, percent: 5.75)
PayoutTable.create(place: 7, players_paid: 10, percent: 3.75)
PayoutTable.create(place: 8, players_paid: 10, percent: 3)
PayoutTable.create(place: 9, players_paid: 10, percent: 2.25)
PayoutTable.create(place: 10, players_paid: 10, percent: 2)

PayoutTable.create(place: 1, players_paid: 11, percent: 31.25)
PayoutTable.create(place: 2, players_paid: 11, percent: 19)
PayoutTable.create(place: 3, players_paid: 11, percent: 13.5)
PayoutTable.create(place: 4, players_paid: 11, percent: 10.5)
PayoutTable.create(place: 5, players_paid: 11, percent: 7.5)
PayoutTable.create(place: 6, players_paid: 11, percent: 5.5)
PayoutTable.create(place: 7, players_paid: 11, percent: 3.75)
PayoutTable.create(place: 8, players_paid: 11, percent: 3)
PayoutTable.create(place: 9, players_paid: 11, percent: 2.25)
PayoutTable.create(place: 10, players_paid: 11, percent: 2)
PayoutTable.create(place: 11, players_paid: 11, percent: 1.75)

PayoutTable.create(place: 1, players_paid: 12, percent: 30)
PayoutTable.create(place: 2, players_paid: 12, percent: 19)
PayoutTable.create(place: 3, players_paid: 12, percent: 13.25)
PayoutTable.create(place: 4, players_paid: 12, percent: 10.5)
PayoutTable.create(place: 5, players_paid: 12, percent: 7.5)
PayoutTable.create(place: 6, players_paid: 12, percent: 5.5)
PayoutTable.create(place: 7, players_paid: 12, percent: 3.75)
PayoutTable.create(place: 8, players_paid: 12, percent: 3)
PayoutTable.create(place: 9, players_paid: 12, percent: 2.25)
PayoutTable.create(place: 10, players_paid: 12, percent: 1.75)
PayoutTable.create(place: 11, players_paid: 12, percent: 1.75)
PayoutTable.create(place: 12, players_paid: 12, percent: 1.75)
