# frozen_string_literal: true

PayoutLines.destroy_all

PayoutLines.create(place: 1, players_paid: 2, percent: 60)
PayoutLines.create(place: 2, players_paid: 2, percent: 40)

PayoutLines.create(place: 1, players_paid: 3, percent: 50)
PayoutLines.create(place: 2, players_paid: 3, percent: 30)
PayoutLines.create(place: 3, players_paid: 3, percent: 20)

PayoutLines.create(place: 1, players_paid: 4, percent: 45)
PayoutLines.create(place: 2, players_paid: 4, percent: 25)
PayoutLines.create(place: 3, players_paid: 4, percent: 18)
PayoutLines.create(place: 4, players_paid: 4, percent: 12)

PayoutLines.create(place: 1, players_paid: 5, percent: 40)
PayoutLines.create(place: 2, players_paid: 5, percent: 23)
PayoutLines.create(place: 3, players_paid: 5, percent: 16)
PayoutLines.create(place: 4, players_paid: 5, percent: 12)
PayoutLines.create(place: 5, players_paid: 5, percent: 9)

PayoutLines.create(place: 1, players_paid: 6, percent: 38)
PayoutLines.create(place: 2, players_paid: 6, percent: 22)
PayoutLines.create(place: 3, players_paid: 6, percent: 15)
PayoutLines.create(place: 4, players_paid: 6, percent: 11)
PayoutLines.create(place: 5, players_paid: 6, percent: 8)
PayoutLines.create(place: 6, players_paid: 6, percent: 6)

PayoutLines.create(place: 1, players_paid: 7, percent: 35)
PayoutLines.create(place: 2, players_paid: 7, percent: 21)
PayoutLines.create(place: 3, players_paid: 7, percent: 15)
PayoutLines.create(place: 4, players_paid: 7, percent: 11)
PayoutLines.create(place: 5, players_paid: 7, percent: 8)
PayoutLines.create(place: 6, players_paid: 7, percent: 6)
PayoutLines.create(place: 7, players_paid: 7, percent: 4)

PayoutLines.create(place: 1, players_paid: 8, percent: 33.5)
PayoutLines.create(place: 2, players_paid: 8, percent: 20)
PayoutLines.create(place: 3, players_paid: 8, percent: 14.5)
PayoutLines.create(place: 4, players_paid: 8, percent: 11)
PayoutLines.create(place: 5, players_paid: 8, percent: 8)
PayoutLines.create(place: 6, players_paid: 8, percent: 6)
PayoutLines.create(place: 7, players_paid: 8, percent: 4)
PayoutLines.create(place: 8, players_paid: 8, percent: 3)

PayoutLines.create(place: 1, players_paid: 9, percent: 32)
PayoutLines.create(place: 2, players_paid: 9, percent: 19.5)
PayoutLines.create(place: 3, players_paid: 9, percent: 14)
PayoutLines.create(place: 4, players_paid: 9, percent: 11)
PayoutLines.create(place: 5, players_paid: 9, percent: 8)
PayoutLines.create(place: 6, players_paid: 9, percent: 6)
PayoutLines.create(place: 7, players_paid: 9, percent: 4)
PayoutLines.create(place: 8, players_paid: 9, percent: 3)
PayoutLines.create(place: 9, players_paid: 9, percent: 2.5)

PayoutLines.create(place: 1, players_paid: 10, percent: 31.75)
PayoutLines.create(place: 2, players_paid: 10, percent: 19.25)
PayoutLines.create(place: 3, players_paid: 10, percent: 13.75)
PayoutLines.create(place: 4, players_paid: 10, percent: 10.75)
PayoutLines.create(place: 5, players_paid: 10, percent: 7.75)
PayoutLines.create(place: 6, players_paid: 10, percent: 5.75)
PayoutLines.create(place: 7, players_paid: 10, percent: 3.75)
PayoutLines.create(place: 8, players_paid: 10, percent: 3)
PayoutLines.create(place: 9, players_paid: 10, percent: 2.25)
PayoutLines.create(place: 10, players_paid: 10, percent: 2)

PayoutLines.create(place: 1, players_paid: 11, percent: 31.25)
PayoutLines.create(place: 2, players_paid: 11, percent: 19)
PayoutLines.create(place: 3, players_paid: 11, percent: 13.5)
PayoutLines.create(place: 4, players_paid: 11, percent: 10.5)
PayoutLines.create(place: 5, players_paid: 11, percent: 7.5)
PayoutLines.create(place: 6, players_paid: 11, percent: 5.5)
PayoutLines.create(place: 7, players_paid: 11, percent: 3.75)
PayoutLines.create(place: 8, players_paid: 11, percent: 3)
PayoutLines.create(place: 9, players_paid: 11, percent: 2.25)
PayoutLines.create(place: 10, players_paid: 11, percent: 2)
PayoutLines.create(place: 11, players_paid: 11, percent: 1.75)

PayoutLines.create(place: 1, players_paid: 12, percent: 30)
PayoutLines.create(place: 2, players_paid: 12, percent: 19)
PayoutLines.create(place: 3, players_paid: 12, percent: 13.25)
PayoutLines.create(place: 4, players_paid: 12, percent: 10.5)
PayoutLines.create(place: 5, players_paid: 12, percent: 7.5)
PayoutLines.create(place: 6, players_paid: 12, percent: 5.5)
PayoutLines.create(place: 7, players_paid: 12, percent: 3.75)
PayoutLines.create(place: 8, players_paid: 12, percent: 3)
PayoutLines.create(place: 9, players_paid: 12, percent: 2.25)
PayoutLines.create(place: 10, players_paid: 12, percent: 1.75)
PayoutLines.create(place: 11, players_paid: 12, percent: 1.75)
PayoutLines.create(place: 12, players_paid: 12, percent: 1.75)
